-- FIX coherencia código FUNDAE: crear grupo (nombre=c_fundae) + añadir alumnos.
-- 39 cursos. Incluye Eduardo Q1 (034-01,id104) y Q2 (093-01,id175). Reversible.
CREATE TABLE IF NOT EXISTS mdl_groups_bak_20260806 AS SELECT * FROM mdl_groups;
CREATE TABLE IF NOT EXISTS mdl_groups_members_bak_20260806 AS SELECT * FROM mdl_groups_members;
START TRANSACTION;
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3210,'','034-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5682,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (4044,'','093-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5682,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3196,'','699-6991','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5733,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3197,'','700-7001','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5734,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3198,'','701-7011','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5735,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3199,'','697-6971','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5736,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3200,'','696-6961','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5733,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3201,'','698-6981','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5735,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3224,'','707-7071','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5737,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3239,'','717-7171','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5819,UNIX_TIMESTAMP(),'',0),(@gid,5820,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3240,'','720-7201','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5827,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3241,'','718-7181','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5821,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3242,'','719-7191','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5823,UNIX_TIMESTAMP(),'',0),(@gid,5822,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3243,'','707-7072','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5824,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (4023,'','001-01525/00001','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5864,UNIX_TIMESTAMP(),'',0),(@gid,5863,UNIX_TIMESTAMP(),'',0),(@gid,5862,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (4024,'','001-01526/00001','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5865,UNIX_TIMESTAMP(),'',0),(@gid,5866,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3272,'','066-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5681,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3133,'','009-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5524,UNIX_TIMESTAMP(),'',0),(@gid,5003,UNIX_TIMESTAMP(),'',0),(@gid,5530,UNIX_TIMESTAMP(),'',0),(@gid,5472,UNIX_TIMESTAMP(),'',0),(@gid,5030,UNIX_TIMESTAMP(),'',0),(@gid,5510,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3147,'','009-02','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5482,UNIX_TIMESTAMP(),'',0),(@gid,5491,UNIX_TIMESTAMP(),'',0),(@gid,5476,UNIX_TIMESTAMP(),'',0),(@gid,5514,UNIX_TIMESTAMP(),'',0),(@gid,5506,UNIX_TIMESTAMP(),'',0),(@gid,5515,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3153,'','009-03','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4982,UNIX_TIMESTAMP(),'',0),(@gid,5466,UNIX_TIMESTAMP(),'',0),(@gid,5322,UNIX_TIMESTAMP(),'',0),(@gid,5015,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3140,'','009-04','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5490,UNIX_TIMESTAMP(),'',0),(@gid,5007,UNIX_TIMESTAMP(),'',0),(@gid,5481,UNIX_TIMESTAMP(),'',0),(@gid,4981,UNIX_TIMESTAMP(),'',0),(@gid,5005,UNIX_TIMESTAMP(),'',0),(@gid,5498,UNIX_TIMESTAMP(),'',0),(@gid,4989,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3148,'','009-05','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4983,UNIX_TIMESTAMP(),'',0),(@gid,4988,UNIX_TIMESTAMP(),'',0),(@gid,5516,UNIX_TIMESTAMP(),'',0),(@gid,5507,UNIX_TIMESTAMP(),'',0),(@gid,5518,UNIX_TIMESTAMP(),'',0),(@gid,5509,UNIX_TIMESTAMP(),'',0),(@gid,5512,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3149,'','010-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5533,UNIX_TIMESTAMP(),'',0),(@gid,5041,UNIX_TIMESTAMP(),'',0),(@gid,5012,UNIX_TIMESTAMP(),'',0),(@gid,5474,UNIX_TIMESTAMP(),'',0),(@gid,5505,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3154,'','010-02','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5499,UNIX_TIMESTAMP(),'',0),(@gid,5014,UNIX_TIMESTAMP(),'',0),(@gid,5039,UNIX_TIMESTAMP(),'',0),(@gid,5483,UNIX_TIMESTAMP(),'',0),(@gid,5465,UNIX_TIMESTAMP(),'',0),(@gid,4987,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3134,'','010-03','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4886,UNIX_TIMESTAMP(),'',0),(@gid,5478,UNIX_TIMESTAMP(),'',0),(@gid,5006,UNIX_TIMESTAMP(),'',0),(@gid,4991,UNIX_TIMESTAMP(),'',0),(@gid,5479,UNIX_TIMESTAMP(),'',0),(@gid,5532,UNIX_TIMESTAMP(),'',0),(@gid,5504,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3137,'','010-04','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5323,UNIX_TIMESTAMP(),'',0),(@gid,4956,UNIX_TIMESTAMP(),'',0),(@gid,5013,UNIX_TIMESTAMP(),'',0),(@gid,4959,UNIX_TIMESTAMP(),'',0),(@gid,4973,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3141,'','010-05','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5470,UNIX_TIMESTAMP(),'',0),(@gid,4992,UNIX_TIMESTAMP(),'',0),(@gid,5032,UNIX_TIMESTAMP(),'',0),(@gid,5031,UNIX_TIMESTAMP(),'',0),(@gid,5034,UNIX_TIMESTAMP(),'',0),(@gid,5508,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3144,'','010-06','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4977,UNIX_TIMESTAMP(),'',0),(@gid,5464,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3150,'','010-07','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4997,UNIX_TIMESTAMP(),'',0),(@gid,5040,UNIX_TIMESTAMP(),'',0),(@gid,4939,UNIX_TIMESTAMP(),'',0),(@gid,5519,UNIX_TIMESTAMP(),'',0),(@gid,5513,UNIX_TIMESTAMP(),'',0),(@gid,5036,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3136,'','011-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4963,UNIX_TIMESTAMP(),'',0),(@gid,4971,UNIX_TIMESTAMP(),'',0),(@gid,4954,UNIX_TIMESTAMP(),'',0),(@gid,5018,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3145,'','011-02','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4966,UNIX_TIMESTAMP(),'',0),(@gid,4980,UNIX_TIMESTAMP(),'',0),(@gid,4958,UNIX_TIMESTAMP(),'',0),(@gid,4936,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3151,'','012-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5017,UNIX_TIMESTAMP(),'',0),(@gid,4998,UNIX_TIMESTAMP(),'',0),(@gid,4943,UNIX_TIMESTAMP(),'',0),(@gid,4937,UNIX_TIMESTAMP(),'',0),(@gid,5517,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3152,'','012-02','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5022,UNIX_TIMESTAMP(),'',0),(@gid,4955,UNIX_TIMESTAMP(),'',0),(@gid,5467,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3135,'','012-03','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5001,UNIX_TIMESTAMP(),'',0),(@gid,5523,UNIX_TIMESTAMP(),'',0),(@gid,4970,UNIX_TIMESTAMP(),'',0),(@gid,4961,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3138,'','012-04','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4964,UNIX_TIMESTAMP(),'',0),(@gid,4986,UNIX_TIMESTAMP(),'',0),(@gid,5485,UNIX_TIMESTAMP(),'',0),(@gid,5000,UNIX_TIMESTAMP(),'',0),(@gid,4940,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3142,'','012-05','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4947,UNIX_TIMESTAMP(),'',0),(@gid,4884,UNIX_TIMESTAMP(),'',0),(@gid,4888,UNIX_TIMESTAMP(),'',0),(@gid,5531,UNIX_TIMESTAMP(),'',0),(@gid,5059,UNIX_TIMESTAMP(),'',0),(@gid,5033,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3146,'','012-06','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,4978,UNIX_TIMESTAMP(),'',0),(@gid,4930,UNIX_TIMESTAMP(),'',0),(@gid,4929,UNIX_TIMESTAMP(),'',0),(@gid,4974,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3139,'','013-01','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5493,UNIX_TIMESTAMP(),'',0),(@gid,5674,UNIX_TIMESTAMP(),'',0),(@gid,4979,UNIX_TIMESTAMP(),'',0),(@gid,4969,UNIX_TIMESTAMP(),'',0),(@gid,5486,UNIX_TIMESTAMP(),'',0),(@gid,5002,UNIX_TIMESTAMP(),'',0);
INSERT INTO mdl_groups (courseid,idnumber,name,description,descriptionformat,enrolmentkey,picture,hidepicture,timecreated,timemodified) VALUES (3143,'','013-02','',1,'',0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP());
SET @gid=LAST_INSERT_ID();
INSERT INTO mdl_groups_members (groupid,userid,timeadded,component,itemid) VALUES (@gid,5021,UNIX_TIMESTAMP(),'',0),(@gid,4965,UNIX_TIMESTAMP(),'',0),(@gid,4885,UNIX_TIMESTAMP(),'',0),(@gid,5487,UNIX_TIMESTAMP(),'',0),(@gid,4993,UNIX_TIMESTAMP(),'',0),(@gid,5016,UNIX_TIMESTAMP(),'',0);
SELECT COUNT(*) grupos_nuevos FROM mdl_groups WHERE timecreated>=UNIX_TIMESTAMP()-180;
-- Esperado: 39 grupos, 136 miembros. Si cuadra: COMMIT;  si no: ROLLBACK;
